### ISSUE TITLE
HTML CSS

### ISSUE THREAD

**Issue by bigggge** [ALetterSong/Note#2]
### DOCTYPE作用？标准模式与混杂模式各有什么区别?

文档类型，它的目的是要告诉标准通用标记语言解析器，它应该使用什么样的**文档类型定义（DTD）来解析文档**。

**标准模式**（standards mode）：浏览器**根据标准规约**来渲染页面。

**混杂模式**（quirks mode）：浏览器采用更加宽松的、**向后兼容**的方式来渲染页面。

混杂模式下，浏览器会模仿旧浏览器的行为，比如IE6，在此基础上兼容新的标准特性。 混杂模式又称兼容模式。

### HTML5 的 `<!DOCTYPE HTML>`？

HTML5的doctype非常简单。表明你的HTML内容使用HTML5，只需要简单的使用：

`<!DOCTYPE html>`

这样做会让目前还不支持的HTML5的浏览器采用**标准模式**解析，这意味着他们会解析那些HTML5中兼容的旧的HTML的标签的部分，而忽略他们不支持HTML5的新特性。

**它更容易被记住并且减少必须下载的字节数**。

### 行内元素有哪些？块级元素有哪些？ 空(void)元素有那些？

大多数 HTML 元素被定义为**块级元素**或**内联元素**。

**块级元素**在浏览器显示时，通常会以新行来开始（和结束）
如：`<div>,<h1>,<p>,<ul>,<table>`

**内联元素**在显示时通常不会以新行开始
如：`<span>,<b>,<td>,<a>,<img>`

**空元素**可能是 HTML，SVG里的一个不可能存在子节点的元素，通常在一个空元素上使用一个闭标签是无效的
如：`<hr>,<img>,<input>`

### 页面导入样式时，使用link和@import有什么区别？

与 `<link>`相比, `@import` 更慢，需要额外的页面请求，并且可能引发其他的意想不到的问题

link引用的CSS文件会同时被加载，而@import引用的CSS 会等到页面全部被下载完再被加载

### 浏览器内核,浏览器的工作原理？

**渲染(排版)引擎**

WebKit 是一种用来让网页浏览器绘制网页的**排版引擎**。它被用于 Apple Safari。其分支被用于基于 Chromuim 的网页浏览器

**JavaScript引擎**

Google 的 V8 引擎 是用 C++ 编写的，它也能够编译并执行 JavaScript 源代码、处理内存分配和垃圾回收

**浏览器的渲染过程**

1.处理 HTML 标记并构建 DOM 树。  
2.处理 CSS 标记并构建 CSSOM 树。
3.将 DOM 与 CSSOM 合并成一个渲染树。  
4.根据渲染树来布局(layout)，以计算每个节点的几何信息（在屏幕中的位置）。  
5.将各个节点绘制(paint)到屏幕上。  

![](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/images/analysis-dom-css-js.png)

### 浏览器是怎样解析CSS选择器的？

浏览器css匹配核心算法是以 从右到左 方式匹配节点的。

试想一下，如果采用 从左到右 的方式读取css规则，那么大多数规则读到最后（最右）才会发现是不匹配的，这样会做费时耗能，最后有很多都是无用的；而如果采取 从右到左 的方式，那么**只要发现最右边选择器不匹配，就可以直接舍弃了**，避免了许多无效匹配。

### style标签写在body后与body前有什么区别？

写在body后会重新渲染整个页面

### 把script标签放在body结束标签之前和之后有什么区别？浏览器会如何解析它们？

将`<script>`写在`</body>`之后，最终的DOM树里，`<script>`元素还是会成为`</body>`的子节点  

### Reflow 和 Repaint

**reflow**

在渲染过程中称为**回流**，发生在 Render Tree 阶段，它主要是用来确定每个元素在屏幕上的几何属性

```javascript
let styles = document.getElementsByTagName('body')[0].style;
styles.margin = '40px'; // reflow,repaint
styles.border = '40px solid #f00'; // reflow,repaint
styles.padding = '40px'; // reflow,repaint
styles.width = '300px'; // reflow,repaint
```

**repaint**

在渲染过程中称为**重绘**，repaint 执行过程就是将元素的颜色、背景等属性绘制出来。

```javascript
let styles = document.getElementsByTagName('body')[0].style;
styles.color = '#fff'; // repaint
styles.backgroundColor = '#f00'; // repaint
```

> 添加预定义的 class，减少逐行修改元素样式的行为可以减少 reflow 和 repaint

### HTML5有哪些新特性、移除了那些元素？如何处理HTML5新标签的浏览器兼容问题？如何区分 HTML 和 HTML5？

HTML5 是最新的 HTML 标准。

HTML5 拥有新的语义、图形以及多媒体元素。

HTML5 提供的新元素和新的 API 简化了 web 应用程序的搭建。

```javascript
(function() {
    // 页面头部
    var a = ['section', 'article', 'nav', 'header', 'footer' /* 其他HTML5元素 */];
    for (var i = 0, j = a.length; i < j; i++) {
        document.createElement(a[i]);
    }   
})();
```

### 简述一下你对HTML语义化的理解？

1.语义化就是**用正确的标签做正确的事情**，让页面的**内容结构化**，便于对浏览器、搜索引擎解析；

2.在没有样式的情况下也以一定格式显示，容易阅读。

3.搜索引擎爬虫依赖于标记来确定关键字的权重，**利于 SEO**。也**便于阅读维护代码**。

### HTML5的离线储存怎么使用，工作原理能不能解释一下？

HTML5 提供一种 应用程序缓存 机制，使得基于web的应用程序可以离线运行。

	<html manifest="example.appcache"> 
	  ...
	</html>

>该特性已经从 Web 标准中删除,Service Workers用于替代它

### 请描述一下 cookies，sessionStorage 和 localStorage 的区别？

|   特性   |                  Cookie                  |              localStorage |                           sessionStorage |
| :----: | :--------------------------------------: | ------------------------: | ---------------------------------------: |
|  生命周期  | 一般由服务器通过Set-Cookie字段生成，可设置失效时间。如果在浏览器端生成Cookie，默认是关闭浏览器后失效 |              除非被清除，否则永久保存 | 仅在当前会话下有效，关闭页面或浏览器后被清除（现代浏览器已经具备了重新打开最近关闭的标签页后恢复上次浏览会话的功能） |
| 存放数据大小 |            4kb左右（一般不超过4095字节）            |                    一般为5MB |                                   一般为5MB |
| 与服务器通信 |  每次都会携带在HTTP头中，如果使用cookie保存过多数据会带来性能问题   | 仅在客户端（即浏览器）中保存，不参与和服务器的通信 |                仅在客户端（即浏览器）中保存，不参与和服务器的通信 |

>每个 HTTP 请求都会带着 Cookie 的信息，所以 Cookie 当然是能精简就精简，比较常用的一个应用场景就是判断用户是否登录。针对登录过的用户，服务器端会在他登录时往 Cookie 中插入一段加密过的唯一辨识单一用户的辨识码，下次只要读取这个值就可以判断当前用户是否登录啦。

### iframe有那些缺点？

1.iframe会阻塞主页面的Onload事件；
2.搜索引擎的检索程序无法解读这种页面，不利于SEO;
3.会影响页面的并行加载。

### Label的作用是什么？是怎么用的？

`<label> `标签为 input 元素定义标注（标记）。

label 元素为鼠标用户改进了可用性。如果**在 label 元素内点击文本，就会触发此控件**。

`<label>` 标签的 for 属性应当与相关元素的 id 属性相同。

### HTML5的form如何关闭自动完成功能？

`autocomplete="off"`

### 如何实现浏览器内多个标签页之间的通信? 

使用**cookie**

使用web worker

使用**localeStorage**和**sessionStorage**

### WebSocket如何兼容低浏览器？

HTTP 轮询 

### 页面可见性（Page Visibility API） 可以有哪些用途？

	document.addEventListener('visibilitychange', function () {
	        var isHidden = document.hidden;
	        if (isHidden) {
	            document.title = 'hidden'
	        } else {
	            document.title = 'visible'
	        }
	    });

### 如何在页面上实现一个圆形的可点击区域？

图像映射技术

```html
<img src="images/circle.png" rel="nofollow" target="_blank" usemap="#map"/>
<map name="map" id="map">
    <area shape="circle" coords="100,100,50" href="http://www.baidu.com" rel="nofollow" target="_blank"/>
</map>
```

boader-radius

```html
<style>
    #circle{
        background:red;
        width:100px;
        height:100px;
        border-radius:50%;
    }
</style>
<div id="circle" onclick="alert('click')"></div>
```

JS 判断

```javascript
  document.onclick = function (e) {
        var r = 50;
        var x1 = 50;
        var y1 = 50;
        var x2 = e.clientX;
        var y2 = e.clientY;
        var distance = Math.abs(Math.sqrt(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2)));
        if (distance <= 50)
            alert("click");
    }
```

### b与strong的区别、i与em的区别？

`<b>  <i>` 是视觉要素，分别表示无意义的加粗，无意义的斜体

`<em> <strong>`  是表达要素, `<em>` （emphasized text）表示一般的强调文本，而 `<strong>`表示比 `<em>` 语义更强的的强调文本

### textContent innerHtml innerText  

```
<div id="test">
    <span style="color:red">test1</span>test2
</div>
```

![](http://7xq3d5.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-04-15%20%E4%B8%8B%E5%8D%882.42.01.png?imageView2/2/w/380)

### 介绍一下标准的CSS的盒子模型？

CSS 框模型 (Box Model) **规定了元素框处理元素内容、内边距、边框 和 外边距 的方式**。

![](http://w3help.org/zh-cn/kb/006/006/boxdim.png)

### CSS选择器有哪些？哪些属性可以继承？

**类选择器**:`.important {font-weight:bold;}`

**ID选择器**:`#intro {font-weight:bold;}`

**属性选择器**:

`a[href="http://www.w3school.com.cn/about_us.asp"]` {color: red;} 将指向 Web 服务器上某个指定文档的超链接变成红色

`[title~=flower]`	选择 title 属性包含单词 "flower" 的所有元素。

`[abc^="def"]` 选择 abc 属性值以 “def” 开头的所有元素

`[abc$="def"]` 选择 abc 属性值以 “def” 结尾的所有元素

`[abc*="def"]` 选择 abc 属性值中包含子串 “def” 的所有元素

>[attribute~=value] matches any entry in a space-delimited list.
>It matches attribute="a value b", but not attribute="a valueb".

>[attribute*=value] matches any substring.
>It matches attribute="a value b" and attribute="a valueb", but not attribute="x".

**后代选择器:**`h1 em { color: red; }`

**子元素选择器**:

```
//选择只作为 h1 元素子元素的 strong 元素
h1 > strong {color:red;}
```
**相邻兄弟选择器**:

```
//增加紧接在 h1 元素后出现的段落的上边距
h1 + p {margin-top:50px;}
```

**伪类**:

```
:active 向被激活的元素添加样式。
:focus 向拥有键盘输入焦点的元素添加样式。
:hover 当鼠标悬浮在元素上方时，向元素添加样式。
:link 向未被访问的链接添加样式。
:visited 向已被访问的链接添加样式。
:first-child 向元素的第一个子元素添加样式。
:lang 向带有指定 lang 属性的元素添加样式。
```

**伪元素**:

```
:first-letter 向文本的第一个字母添加特殊样式。
:first-line 向文本的首行添加特殊样式。
:before 在元素之前添加内容。
:after 在元素之后添加内容。
```

**可继承的样式**： font-size font-family color  

**不可继承的样式**： border padding margin width height等

### CSS定义的权重和CSS优先级算法如何计算？

当优先级与多个CSS声明中任意一个声明的优先级相等的时候，CSS中最后的那个声明将会被应用到元素上。

内联样式表（标签内部）> 内部样式表（当前文件中）> 外部样式表（外部文件中）

![](http://7xq3d5.com1.z0.glb.clouddn.com/%E9%80%89%E6%8B%A9%E5%99%A8%E6%9D%83%E9%87%8D.jpg)

### display有哪些值？说明他们的作用。

**none** 关闭一个元素的显示（**对布局没有影响**）；其所有后代元素都也被会被关闭显示。文档渲染时，**该元素如同不存在**

**inline** 该元素生成一个或多个行内元素盒,设置了该属性之后**设置高度、宽度都无效**，同时text-align属性设置也无效，但是设置了line-height会让inline元素居中

>行内元素的padding-top、padding-bottom、margin-top、margin-bottom属性设置是无效的
>
>行内元素的padding-left、padding-right、margin-left、margin-right属性设置是有效的
>
>行内元素的padding-top、padding-bottom从显示的效果上是增加的，但其实设置的是无效的。并不会对他周围的元素产生任何影响。

**block** 设置元素为块级元素，如果不指定宽高，默认会继承父元素的宽度，并且**独占一行**，即使宽度有剩余也会独占一行，高度一般以子元素撑开的高度为准，当然也可以自己**设置宽度和高度**

**inline-block**

行内块元素

**table-row**

此元素会作为一个表格行显示（类似 `<tr>`）

**table-cell**

此元素会作为一个表格单元格显示（类似 `<td>` 和 `<th>`）

**flex**

The element behaves like a block element and lays out its content according to the flexbox model.

### position有哪些值？说明他们的作用？

position 属性规定元素的定位类型。

**static**

该框是一个常规框，布局根据常规流。'left' 、'right'、'bottom' 和 'top' 属性不适用。

**relative**

框的位置根据常规流计算（被称为常规流中的位置）。然后框相对于它的常规位置而偏移。如果框 B 是相对定位的，其后框的定位计算并不考虑 B 的偏移。

![](http://w3help.org/zh-cn/kb/009/009/relative_position.png)

>注意，相对定位的元素处于常规流中，没有脱离常规流

**absolute**

框的位置（可能还有它的尺寸）是由'left'，'right'，'top'和'bottom'特性决定。这些特性指定了框相对于它包含块的偏移量。 绝对定位的框从**常规流中脱离**。这意味着它们对其后的兄弟元素的定位没有影响。另外，尽管绝对定位框有外边距(margin)， 它们**不会和其它任何外边距发生折叠**（Collapsing margins）

![](http://w3help.org/zh-cn/kb/009/009/absolute_position.png)

**fixed**

生成绝对定位的元素，相对于**浏览器窗口**进行定位。
元素的位置通过 "left", "top", "right" 以及 "bottom" 属性进行规定。

### 什么是外边距合并？

外边距合并指的是，当两个垂直外边距相遇时，它们将形成一个外边距。
合并后的外边距的高度等于两个发生合并的外边距的高度中的较大者。

![](http://www.w3school.com.cn/i/ct_css_margin_collapsing_example_1.gif)

![](http://www.w3school.com.cn/i/ct_css_margin_collapsing_example_2.gif)

1.两个或多个毗邻的**普通流中的块元素垂直方向上**的 margin 会折叠

2.**浮动元素、inline-block 元素、绝对定位元素**的 margin **不会**和垂直方向上其他元素的 margin 折叠

3.创建了**BFC**的元素，**不会**和它的子元素发生 margin 折叠

> 元素自身的 margin-bottom 和 margin-top 相邻时也会折叠

### 简述包含块，absolute的containing block(包含块)计算方式跟正常流有什么不同？

![](http://upload-images.jianshu.io/upload_images/257925-b6e184ca0d73076e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**根元素**存在的包含块，被叫做**初始包含块**

- 根元素：初始包含块
- static/relative 元素：由它最近的 block、table cell(类似 `<td>` 和 `<th>`) 或者 inline-block 祖先元素的内容框（content edge）
- fixed元素： 可视窗口
- absolute 元素：

  - 祖先元素为 static：初始包含块
  - 祖先元素为 absolute/relative/fixed：

     - block元素：祖先元素的内边距边界（padding edge）
     - inline元素：
         - direction为ltr：包含块的顶、左边是祖先元素生成的第一个框的顶、左内边距边界(padding edges) ，右、下边是祖先元素生成的最后一个框的右、下内边距边界(padding edges)
         - direction为rtl：包含块的顶、右边是祖先元素生成的第一个框的顶、右内边距边界 (padding edges) ，左、下边是祖先元素生成的最后一个框的左、下内边距边界 (padding edges)

### 请介绍下CSS定位体系

CSS 有三种基本的定位机制：

**普通流，常规流(Normal flow)**

普通流中的元素的位置由元素在HTML中的位置决定。

**块级框**从上到下一个接一个地排列，框之间的垂直距离是由框的垂直外边距计算出来。

**行内框**在一行中水平布置。可以使用水平内边距、边框和外边距调整它们的间距。但是，**垂直内边距、边框和外边距不影响行内框的高度**。由一行形成的水平框称为行框（Line Box），**行框的高度**总是足以容纳它包含的所有行内框。不过，设置**行高**可以增加这个框的高度。

>在 CSS2.1中，常规流包括块框( block boxes )的块格式化( block formatting )， 行内框( inline boxes )的行内格式化( inline formatting )，块框或行内框的相对定位，以及插入框的定位。
>

**浮动(Floats)**

浮动的框可以向左或向右移动，直到它的外边缘碰到**包含框**或**另一个浮动框的边框**为止。
由于**浮动框不在文档的普通流中**，所以文档的普通流中的块框表现得就像浮动框不存在一样。

**绝对定位(Absolute positioning)**

在绝对定位模型中，一个框整个地从常规流中脱离，并**根据它的包含块来分配其位置**。

### 对BFC规范(块级格式化上下文：block formatting context)的理解？

什么是BFC(Block formatting contexts)?

- **根元素**

- **浮动元素**
- **绝对定位元素**
- **块级容器** （display 为 inline-block，table-cell，table-caption）的元素
- overflow 不为 visible 的**块级元素**

都会为他们的内容创建新的BFC（块级格式上下文）。

在BFC中，盒子从顶端开始垂直地一个接一个地排列，两个盒子之间的垂直的间隙是由他们的 margin 值所决定的。**在一个BFC中，两个相邻的块级盒子的垂直外边距会产生折叠**。

通俗理解：

BFC是一个独立的布局环境，我们可以理解为一个箱子，箱子里面物品的摆放是不受外界的影响的。
**BFC中的元素的布局是不受外界的影响**（我们往往利用这个特性来消除浮动元素对非浮动元素的影响。）并且在一个BFC中，块盒与行盒（行盒由一行中所有的内联元素所组成）都会垂直的沿着其父元素的边框排列。

BFC的运用  
1.    
      用于清除（闭合）浮动
      [在线演示](http://runjs.cn/code/3mnjht9r)

![](http://upload-images.jianshu.io/upload_images/257925-19b8c81e18452dd6.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

info类里面的文字受到了浮动元素的影响，但这并不是我们所期望的。此时我们可以为P元素的内容建立一个BFC，让其内容消除对外界浮动元素的影响。根据上文所知，只要给info元素添加`overflow:hidden`;即可为其内容建立新的BFC。  

2.
解决margin叠加问题，可以给元素添加一个父元素，让它触发BFC。

```css
.BFC{
    overflow:hidden;
}
```

<script async src="//jsfiddle.net/gothic/B6E8F/embed/"></script>

###CSS里的visibility属性有个collapse属性值是干嘛用的？

**visible**	默认值。元素是可见的。

**hidden**	元素是不可见的。

**collapse**	当在表格元素中使用时，此值可删除一行或一列，但是它不会影响表格的布局。被行或列占据的空间会留给其他内容使用。如果此值被用在其他的元素上，会呈现为 "hidden"。

### position跟display、margin collapse、overflow、float这些特性相互叠加后会怎么样？

http://www.cnblogs.com/jackyWHJ/p/3756087.html

### 你对baseline，line-height是如何理解的？

**基线、底线、顶线**

![](http://images.cnblogs.com/cnblogs_com/rainman/139529/o_line_height.png)

- 行高指的是文本行的基线间的距离
- 基线并不是汉字的下端沿，而是英文字母"x"的下端沿

**行距、行高**

![](http://images.cnblogs.com/cnblogs_com/rainman/139529/o_text_018.gif)

**内容区**

![](http://images.cnblogs.com/cnblogs_com/rainman/139529/o_text_019.gif)

- 底线和顶线包裹的区域，实际中不一定看得到，但却是存在

**行内框**

![](http://images.cnblogs.com/cnblogs_com/rainman/139529/o_text_020.gif)

- 行内框只是一个概念，它无法显示出来，但是它又确实存在
- 它的高度就是行高
- 在没有其他因素（padding）影响的时候，行内框等于内容区域

**行框**

![](http://images.cnblogs.com/cnblogs_com/rainman/139529/o_text_021.gif)

- 行框（line box）。同行内框类似，行框是指本行的一个虚拟的矩形框
- 行框高度等于本行内所有元素中行高最大的值

### vertical-align

该属性定义行内元素的基线相对于该元素所在行的基线的垂直对齐

### box-sizing

**box-sizing **属性用于更改用于计算元素宽度和高度的默认的CSS盒子模型。

例如，假如您需要并排放置两个带边框的框，可通过将 box-sizing 设置为 "border-box"。这可令浏览器呈现出带有指定宽度和高度的框，并把边框和内边距放入框中。

### 请解释一下为什么要清除浮动？清除浮动的方式

**为什么要清除浮动**

一个块级元素的高度如果没有设置height，那么其高度就是由里面的子元素来撑开的，如果子元素使用浮动，**脱离了普通流，那么父元素的高度会将其忽略**，如果不清除浮动，父元素会出现高度不够，那样如果设置border或者background都得不到正确的解析

**清除浮动的方式**

1.使用 clear 属性

- 使用带clear属性的空元素

`<div style="clear:both">`

- 使用:after 伪元素

```
 .clearfix:after {
    content: '';
    display: block;
    clear: both;
  }
```

2.触发浮动元素父元素的**BFC**,如父元素设置 overflow：hidden / overflow：auto

创建了它的元素，会重**新计算其内部元素位置**，从而获得确切高度。这样父容器也就包含了浮动元素高度。

>另外在 IE6 中还需要触发 **hasLayout** ，例如为父元素设置容器宽高或设置 zoom:1。在添加overflow属性后，浮动元素又回到了容器层，把容器高度撑起，达到了清理浮动的效果

### 设置元素浮动后，该元素的display值是多少？

block

### 请说明对 inline-block 的理解，display:inline-block 什么时候会显示间隙？,li与li之间有看不见的空白间隔是什么原因引起的？有什么解决办法？

设置了inline-block属性的元素既拥有了block元素**可以设置width和height**的特性，又保持了**inline元素不换行**的特性

默认情况下，inline元素之间就有空隙出现，所以结合了inline和block属性的inline-block属性自然也有这个特点。

1.CSS trick，如设font-size为0。但此种方法副作用过多

2.删掉空白。缺点，源代码排版会面临困难

3.使用不产生额外空白节点或者支持空白控制的模板语言

http://www.iyunlu.com/view/css-xhtml/64.html

http://www.cnblogs.com/lrzw32/p/4927570.html

### 元素竖向的百分比设定是相对于容器的高度吗？

`padding-top`,`padding-bottom`,`margin-top`,`margin-bottom`等，当按百分比设定它们时，依据的也是父容器的宽度，而不是高度。

### 为什么要初始化CSS样式。

因为浏览器的兼容的问题，不同浏览器有些标签的默认值是不同的，如果没有CSS初始化往往会出现浏览器之间的页面显示差异。

### ::before 和 :after中双冒号和单冒号有什么区别？解释一下这2个伪元素的作用。

单冒号(:)用于CSS3伪类，双冒号(::)用于CSS3伪元素

`:before`在元素的内容之前插入内容

`:after`在元素的内容之后插入内容

### CSS3有哪些新特性？

1.实现圆角（border-radius），阴影（box-shadow）， 

2.文字特效（text-shadow）CSS动画（animation @keyframes）CSS过渡（transition）

3.2D转换 **transform**:rotate(9deg)  scale(0.85,0.90) translate(0px,-30px) skew(-9deg,0deg);// 旋转,缩放,定位,倾斜 

4.新增伪类/伪元素

5.column-count， column-gap

### CSS3 新增伪类/伪元素有那些？

**伪类**是添加到选择器的关键字，指定要选择的元素的特殊状态。

`p:nth-child(2)`	选择属于其父元素的第二个子元素的每个 `<p>` 元素

`p:nth-of-type(2)`选择属于其父元素的第二个`<p>`元素的每个 `<p>` 元素

`:not(p)`选择非`<p>`元素的每个元素

`input:enabled`选择每个启用的`<input>`元素

`input:checked`选择每个被选中的`<input>`元素。

**伪元素**添加到选择器，但不是描述特殊状态，它们允许您为元素的某些部分设置样式。

`::selection`	选择被用户选取的元素部分

>::selection CSS伪元素选择器是CSS第3级选择器的草案，但是在被推荐使用前就被废弃。它现在在第4级伪元素选择器草案中。

### 请解释一下CSS3的Flexbox（弹性盒布局模型）,以及适用场景？

![](https://dn-mhke0kuv.qbox.me/0dd26d8e99257ff36443.png)

https://juejin.im/post/58e3a5a0a0bb9f0069fc16bb

### 实现不使用 border 画出1px高的线

<div style="height:1px;background:red"></div>

### 垂直居中？

```css
<style>
        /*https://www.smashingmagazine.com/2013/08/absolute-horizontal-vertical-centering-css/*/
        /*http://blog.csdn.net/freshlover/article/details/11579669*/
        /*绝对定位居中(Absolute Centering)技术*/
        .div1 {
            height: 200px;
            width: 200px;
            background: #90dbd5;
            margin: auto;
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
        }

        /*变形（Transforms）*/
        .div2 {
            height: 150px;
            width: 150px;
            background: #7be550;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }

        .Center-Container.is-Table {
            display: table;
        }

        .is-Table .Table-Cell {
            display: table-cell;
            vertical-align: middle;
        }

        .is-Table .Center-Block {
            width: 50%;
            margin: 0 auto;
            background: blue;
        }

        /*http://zh.learnlayout.com/flexbox.html*/
        /*CSS3 Flexbox*/
        .flexbox {
            background: #f2f2f2;
            width: 300px;
            height: 500px;
            display: -webkit-flex;
            display: flex;
            -webkit-align-items: center;
            align-items: center;
            -webkit-justify-content: center;
            justify-content: center;
        }
    </style>
```

```html
<div class="div1">div1</div>

<div class="div2">div2</div>

<div class="flexbox">
    <span style="z-index:999; color:blue; font-size:20px;">flexbox</span>
</div>
```

### 用纯CSS创建一个三角形的原理是什么？

```css
.border {  
  width:0px;  //设为0得到尖角
  height:0px;  
  border: 20px solid;  
  border-color: #ADFF2F #BA55D3 #F4A460 #FF0000;  
}  
```
结果如下：

![](http://img.blog.csdn.net/20150123120143031?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvcGlnc3VwZXI=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

将其中三条边设置为 transparent 即可得到三角形

### CSS多列等高如何实现？

**padding-bottom 与 margin-bottom**

```html
<div class="box">
  <div class="sub">
    <p>a</p>
  </div>
  <div class="sub">
    <p>b</p>
    <p>b</p>
  </div>
  <div class="sub">
    <p>c</p>
    <p>c</p>
    <p>c</p>
  </div>
</div>
```

```css
.box {
  width: 500px;
  overflow: hidden;
  margin: 10px auto;
  border: 1px solid #888;
}
.sub {
  box-sizing: border-box;
  float: left;
  width: 33%;
  border: 1px solid orange;
  padding-bottom: 9999px;
  margin-bottom: -9999px;
}
```

**table-cell**

```html
<div class="box">
  <div class="row">
    <div class="cell">该方案利用了所有单元格高度都相等的特性</div>
    <div class="cell">该方案利用了所有单元格高度都相等的特性</div>
    <div class="cell">该方案利用了所有单元格高度都相等的特性该方案利用了所有单元格高度都相等的特性</div>
  </div>
</div>
```

```css
.box {
  width: 600px;
  font-size: 12px;
}
.row {
  display: table-row;
}
.cell {
  display: table-cell;
  width: 33%;
  background-color: #f5f5f5;
}
```

### 请问,我页面上有这么一个布局,有两个div,左边的div有确定宽度,并且是固定的,右边自适应,请问你会怎么实现?

float+margin-left

```css
#aside {
    float: left;
    width: 240px;
    height: 500px;
    background: #ccc;
}

#main {
    height: 500px;
    margin-left: 240px;
    background: orange;
}
```

flex

```css
.main {
  border: 1px solid #000;
  width: 100%;
  height: 100px;
  box-sizing: border-box;
  display: flex;
}

.left {
  background-color: #000;
  flex: 0 0 100px;
  order: -1;
}

.content {
  flex: auto;
  background-color: #f00;
}
```

https://www.zybuluo.com/yacent/note/383948

### 什么是响应式设计？响应式设计的基本原理是什么？移动端的布局用过媒体查询吗？

响应式网站设计(Responsive Web design)的理念是：集中创建页面的图片排版大小，可以智能地根据用户行为以及使用的设备环境进行相对应的布局。

```
@media screen and (min-width:600px) {
  nav {
    float: left;
    width: 25%;
  }
  section {
    margin-left: 25%;
  }
}
@media screen and (max-width:599px) {
  nav li {
    display: inline;
  }
}
```

### 使用 CSS 预处理器吗？

**Sass 特性**

1.使用变量 `$highlight-color: #F90;`

2.嵌套CSS 规则

```
article a {
  color: blue;
  &:hover { color: red }
}
```

3.混合器

```
@mixin rounded-corners {
  -moz-border-radius: 5px;
  -webkit-border-radius: 5px;
  border-radius: 5px;
}

notice {
  background-color: green;
  border: 2px solid #00aa00;
  @include rounded-corners;
}
```

### 经常遇到的浏览器的兼容性有哪些？？

ES6：babel/polyfill

CSS/HTML：没遇到过

### 全屏滚动的原理是什么？用到了CSS的那些属性？

滚动时候通过css的transform属性进行偏移，并结合transition过渡一下效果

```javascript
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>fullpage</title>
    <style type="text/css">
        * {
            margin: 0;
            padding: 0;
        }
        .full-page-container {
            position: fixed;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            transition: all ease 1s;
        }
        .slide1 {
            background-color: rgb(27, 188, 155);
        }
        .slide2 {
            background-color: rgb(255, 153, 0);
        }
        .slide3 {
            background-color: rgb(123, 170, 190);
        }
    </style>
</head>
<body>
<div class="full-page-container">
    <div class="slide slide1">
    </div>
    <div class="slide slide2">
    </div>
    <div class="slide slide3">
    </div>
</div>
<script type="text/javascript">
    function FullPage() {
        this.isScrolling = false;
        this.currentIndex = 1;
    }
    FullPage.prototype.init = function () {
        var _this = this;
        this.container = document.getElementsByClassName('full-page-container')[0];
        var slides = _this.container.querySelectorAll('.slide');
        _this.height = _this.container.clientHeight;
        _this.slidesLength = slides.length;
        slides.forEach(function (slide) {
            slide.style.height = _this.height + 'px'
        });
        _this.container.addEventListener('mousewheel', function (event) {
            if (_this.isScrolling) {
                return false;
            }
            var e = event.originalEvent || event;
            var deltaY = e.deltaY;
            deltaY > 0 ? _this.next() : _this.pre();
        });
        _this.container.addEventListener('webkitTransitionEnd', function () {
            _this.isScrolling = false;
        });
    };
    FullPage.prototype.pre = function () {
        if (this.currentIndex - 1 > 0) {
            this.currentIndex -= 1;
            this.move(this.currentIndex);
        }
    };
    FullPage.prototype.next = function () {
        if ((this.currentIndex + 1) <= this.slidesLength) {
            this.currentIndex += 1;
            this.move(this.currentIndex);
        }
    };
    FullPage.prototype.move = function (index) {
        this.isScrolling = true;
        var distance = -(index - 1) * this.height + 'px';
        this.container.style.transform = 'translateY(' + distance + ')';
    };
    var fullpage = new FullPage();
    fullpage.init();
</script>
</body>
</html>
```

### 视差滚动效果

**background-attachment**: fixed || scroll || inherit

默认是scroll，内容跟着背景走，而视差滚动页面里用fixed，背景相对页面固定而不跟内容滚动。

```html
<!DOCTYPE html>
<html>
<head>
    <style>
        body, html {
            height: 100%;
        }
      
        .parallax {
            /* The image used */
            background-image: url('img_parallax.jpg');
            /* Full height */
            height: 100%;
            /* Create the parallax scrolling effect */
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .parallax.img2 {
            background-image: url('img_parallax3.jpg');
        }
    </style>
</head>
<body>
<div class="parallax"></div>
<div style="height:200px;text-align:center;">
    Scroll Up and Down this page to see the parallax scrolling effect.
    This div is just here to enable scrolling.
    Tip: Try to remove the background-attachment property to remove the scrolling effect.
</div>
<div class="parallax img2"></div>
</body>
</html>
```

>在页面滚动过程中，我们获取页面的scrollTop的值，根据不同参数值去设置各自scene的top值，这样滚动页面的时候，不同的速度就出来了

### 怎么让Chrome支持小于12px 的文字？

`<p style="font-size:10px;transform: scale(0.833)">test 10px</p>`

### GIF, PNG, JPEG, SVG, WebP？

**GIF**

GIF格式适用于对色彩要求不高同时需要文件体积较小的场景，比如企业Logo、线框类的图等。

**PNG**

PNG这种类型的图片就是为了取代GIF图片而生的, 除了GIF不支持动画的优势, 能用PNG的地方就用PNG, 原因是压缩比高,色彩好

**JPEG**

JPEG非常适合用来存储照片，用来表达更生动的图像效果

**SVG**

SVG是矢量图，它的特点是使用XML来描述图片

**WebP**

相同质量的图片，WebP具有更小的文件体积

### 实现瀑布流

纯CSS3实现的瀑布流,CSS3多列属性

```html
<style>
    .container {
        column-width: 160px;
        column-gap: 15px;
    }

    .container div {
        width: 160px;
        margin: 10px 0;
    }
</style>

<div class="container">
    <div><img src="images/P_00.jpg"/></div>
    <div><img src="images/P_01.jpg"/></div>
    <div><img src="images/P_02.jpg"/></div>
</div>
```

### 移动端一像素问题

```css
div{
    height:1px;
    background:#000;
    -webkit-transform: scaleY(0.5);
    -webkit-transform-origin:0 0;
    overflow: hidden;
}
```

### 实现右键菜单

```javascript
document.addEventListener('contextmenu', function (e) {
    alert("You've tried to open context menu"); //here you draw your own menu
    e.preventDefault();
}, false);
```

### CSS优化、提高性能的方法有哪些？

1.压缩

2.选择器性能

3.代码可维护性
